
#     ____            ____                ________          ____                    
#    / __ \___ _   __/ __ \____  _____   / ____/ /_  ____ _/ / /__  ____  ____ ____ 
#   / / / / _ \ | / / / / / __ \/ ___/  / /   / __ \/ __ `/ / / _ \/ __ \/ __ `/ _ \
#  / /_/ /  __/ |/ / /_/ / /_/ (__  )  / /___/ / / / /_/ / / /  __/ / / / /_/ /  __/
# /_____/\___/|___/\____/ .___/____/   \____/_/ /_/\__,_/_/_/\___/_/ /_/\__, /\___/ 
#                      /_/                                             /____/       

####################################
#    Capgemini -  DevOps Challenge      #
####################################


- name: "Execution of jenkins role"
  hosts: jenkins
  
  become: true
  become_user: 1bit  
  roles:
    - ansible-role-jenkins
